workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Build iOS
        script: |
          cd build/jsb-link/frameworks/runtime-src/proj.ios_mac
          xcodebuild -project Xok102.xcodeproj \
            -scheme Xok102-mobile \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/Xok102.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Export IPA
        script: |
          cd build/jsb-link/frameworks/runtime-src/proj.ios_mac
          mkdir Payload
          cp -R $CM_BUILD_DIR/Xok102.xcarchive/Products/Applications/*.app Payload/
          zip -r Xok102.ipa Payload
    artifacts:
      - build/jsb-link/frameworks/runtime-src/proj.ios_mac/Xok102.ipa

